spring.application.name=habit-tracker-backend
# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker
spring.datasource.username=postgres
spring.datasource.password=2016

# Настройки JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect