#spring.application.name=habit-tracker-backend
## Подключение к PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker
#spring.datasource.username=postgres
#spring.datasource.password=2016
#
## Настройки JPA (Hibernate)
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=habit-tracker-backend

# Подключение к PostgreSQL (используем переменные окружения)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Настройки JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect